<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment--2/blob/main/DLA2bPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar vector multiplication

a = torch.rand(1)
b = torch.rand(4, 6)
c = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(c)

tensor([0.2056])
tensor([[0.7847, 0.3242, 0.8594, 0.7294, 0.6756, 0.7735],
        [0.5987, 0.3935, 0.2479, 0.9725, 0.9094, 0.9963],
        [0.5231, 0.2006, 0.1014, 0.3237, 0.6816, 0.9045],
        [0.0908, 0.0197, 0.6833, 0.1385, 0.8535, 0.7276]])
tensor([[0.1613, 0.0666, 0.1767, 0.1499, 0.1389, 0.1590],
        [0.1231, 0.0809, 0.0510, 0.1999, 0.1869, 0.2048],
        [0.1075, 0.0412, 0.0209, 0.0665, 0.1401, 0.1859],
        [0.0187, 0.0040, 0.1405, 0.0285, 0.1755, 0.1496]])


In [ ]:
# Vector vector multiplication

a = torch.rand(2, 4)
b = torch.rand(4, 6)
c= torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(c)

tensor([[0.8073, 0.7092, 0.7345, 0.7350],
        [0.0397, 0.7958, 0.2273, 0.9339]])
tensor([[0.2080, 0.8416, 0.7013, 0.9441, 0.0336, 0.3628],
        [0.7711, 0.7964, 0.7351, 0.8595, 0.4359, 0.4202],
        [0.5925, 0.1833, 0.2533, 0.9173, 0.0815, 0.5937],
        [0.6564, 0.3552, 0.8219, 0.9124, 0.4994, 0.2953]])
tensor([[1.6325, 1.6400, 1.8777, 2.7161, 0.7632, 1.2440],
        [1.3697, 1.0406, 1.4380, 1.7821, 0.8332, 0.7596]])


In [ ]:
# Outer product

a = torch.arange(5)
b = torch.arange(3, 6)  
op= torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(op)

tensor([0, 1, 2, 3, 4])
tensor([3, 4, 5])
tensor([[ 0,  0,  0],
        [ 3,  4,  5],
        [ 6,  8, 10],
        [ 9, 12, 15],
        [12, 16, 20]])


In [ ]:
# Scalar dot product

a = torch.arange(9).reshape(3, 3)
b = torch.arange(6).reshape(3, 2)
sp = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(sp)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor(204)


In [ ]:
# Hadamard product

a = torch.arange(8).reshape(2, 4)
b = torch.arange(4, 12).reshape(2, 4)
hp = torch.einsum('ij, ij -> ij', [a, b])
print(a)
print(b)
print(hp)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  5, 12, 21],
        [32, 45, 60, 77]])


In [ ]:
# Batch matrix multiplication

a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_matrix_mul = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_matrix_mul)

tensor([[[-0.4476, -1.0997, -1.8756, -0.1006, -0.5556],
         [ 0.1199,  0.3324, -1.1917,  0.0031, -1.3100],
         [-0.8157, -0.0212, -1.0283, -0.3902,  0.4457]],

        [[-0.9156, -0.6302, -0.8163, -0.3021, -0.6447],
         [ 0.7042, -0.5001, -0.3725,  0.8084, -2.6468],
         [ 1.3482,  0.0910, -0.5790,  1.4507,  0.1389]],

        [[ 0.5679,  1.0392,  1.2311,  0.2235, -0.8959],
         [-0.2645, -1.2623, -0.2102,  0.8275, -0.5388],
         [-2.1786, -0.4738, -0.0850, -0.6662, -1.3504]]])
tensor([[[ 0.3192,  0.2399],
         [ 0.2602,  0.4140],
         [ 0.0138, -2.1651],
         [-2.3568,  0.5865],
         [-0.0797, -0.2870]],

        [[ 0.4947, -0.2482],
         [ 1.1957, -0.6888],
         [ 0.4933, -1.7492],
         [ 0.7893, -0.0767],
         [-0.0727,  0.2591]],

        [[ 0.6484,  0.5163],
         [ 0.2918, -1.8880],
         [ 0.0317, -0.2934],
         [-1.3810,  0.2712],
         [ 0.5550,  1.5976]]])
tensor([[[-0.1735,  3.5988],
         [ 0.2054,  

In [ ]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
tensor_reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, tensor_reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [ ]:
# Transpose

a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


In [ ]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear_transform = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear_transform)

tensor([[-0.6670, -0.4857,  0.1110],
        [-1.1271, -1.3712, -0.7412]])
tensor([[[ 1.0649, -0.0591, -0.6925, -0.5121],
         [-1.0292, -0.5268,  1.7538, -0.7419],
         [-0.0800, -0.5668,  1.3868, -1.1612]],

        [[ 0.0969,  0.5483, -0.2376,  0.0891],
         [ 2.0558,  0.7923, -0.1878,  0.4751],
         [ 0.3288, -0.2456, -0.1581,  0.9347]],

        [[-1.7431,  1.2076,  0.6249,  1.4328],
         [ 0.7649,  0.2961,  1.5144, -0.1632],
         [-0.6044, -0.0875,  0.8127,  0.3896]]])
tensor([[-1.1190, -0.6122,  0.1096,  1.6205],
        [-0.0770,  0.5838,  0.3097,  0.0342]])
tensor([[ 1.0058,  1.3481, -1.6897],
        [-0.0524, -0.4950, -2.2038]])


In [ ]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.0373, 0.0904, 0.5381, 0.0146, 0.3196],
        [0.3684, 0.1695, 0.0401, 0.3515, 0.0705],
        [0.3472, 0.0074, 0.0200, 0.2715, 0.3538]], grad_fn=<SoftmaxBackward0>)


<ipython-input-16-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[ 1.6091, -0.9768, -0.0382],
         [ 0.7039, -0.6952,  0.9831],
         [ 1.4307,  0.7482,  1.3725],
         [ 0.1971,  0.2918,  1.1721],
         [ 0.1041, -0.6191,  0.7931]],

        [[ 0.8237, -0.0585, -0.1657],
         [-0.8563,  1.5082, -0.2654],
         [-0.2914,  0.4693,  1.2502],
         [-0.4363,  1.4290,  0.9658],
         [-1.0381, -0.2776,  0.7747]]])