<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment--2/blob/main/DLA2bTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
# Scalar vector multiplication

a = tf.random.normal([1])
b = tf.random.normal([2, 3])
c = tf.einsum('k, ij -> ij', a, b)
print(a)
print(b)
print(c)

tf.Tensor([1.7226076], shape=(1,), dtype=float32)
tf.Tensor(
[[-0.9342518   0.43499368  0.46969807]
 [ 0.23835714  0.20810324  0.17501721]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.6093493   0.7493234   0.80910546]
 [ 0.41059583  0.35848022  0.301486  ]], shape=(2, 3), dtype=float32)


In [ ]:
# Vector vector multiplication

a = tf.random.normal([2, 5])
b = tf.random.normal([5, 3])
c = tf.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(c)

tf.Tensor(
[[ 1.1287543   0.9050784   0.5453042  -0.17131087  0.28639725]
 [-0.69838727  0.9572083  -0.00735902  0.6077457  -0.20929974]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[-0.06756408 -0.32423338 -0.93639344]
 [ 0.7388895   1.5911351   1.7158275 ]
 [ 1.4335731  -0.20571099 -0.54707336]
 [ 0.01393555 -1.6334486   1.409535  ]
 [ 0.1959109  -2.3951902  -1.8276837 ]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[ 1.4279442   0.55579877 -0.5672333 ]
 [ 0.7113725   1.2595932   3.539568  ]], shape=(2, 3), dtype=float32)


In [ ]:
# Outer product

a = tf.range(4)
b = tf.range(3, 6)  
op= tf.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(op)

tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor(
[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]], shape=(4, 3), dtype=int32)


In [ ]:
# Scalar dot product

a = tf.range(9)
a = tf.reshape(a, [3, 3])

b = tf.range(6)
b = tf.reshape(b, [3, 2])

sp= tf.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(sp)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(204, shape=(), dtype=int32)


In [ ]:
# Hadamard product

a = tf.range(8)
a = tf.reshape(a, [2, 4])

b = tf.range(4, 12)
b = tf.reshape(b, [2, 4])

hp = tf.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(hp)

tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 4  5  6  7]
 [ 8  9 10 11]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 0  5 12 21]
 [32 45 60 77]], shape=(2, 4), dtype=int32)


In [ ]:
# Batch matrix multiplication

a = tf.random.normal([3, 3, 2])
b = tf.random.normal([3, 2, 2])
batch_matrix_mult = tf.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_matrix_mult)

tf.Tensor(
[[[-0.79831696 -0.5608718 ]
  [-0.6365953  -0.3362866 ]
  [ 0.18526855  1.1763206 ]]

 [[-1.5665962  -0.18959999]
  [ 0.4621799  -0.849461  ]
  [-0.03851611  0.24402697]]

 [[ 0.35076648  0.4867204 ]
  [-1.7544641   0.09368535]
  [ 0.36936083 -0.8807448 ]]], shape=(3, 3, 2), dtype=float32)
tf.Tensor(
[[[-0.14962257 -1.0611172 ]
  [ 0.62892425  0.9148574 ]]

 [[ 0.30756995  0.71091807]
  [-0.33733064  0.30330318]]

 [[ 0.07255354 -0.8906138 ]
  [ 0.6826315   0.6500684 ]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[-0.23329961  0.33399016]
  [-0.11624977  0.36784795]
  [ 0.7120962   0.87957394]]

 [[-0.41788    -1.1712278 ]
  [ 0.42870188  0.0709278 ]
  [-0.09416418  0.04663236]]

 [[ 0.35770002  0.00400409]
  [-0.06334002  1.6234518 ]
  [-0.5744257  -0.90150225]]], shape=(3, 3, 2), dtype=float32)


In [ ]:
# Tensor reduction

a = tf.random.normal([2, 3, 5, 7])
b = tf.random.normal([4, 1, 3, 11, 5])
tensor_reduction = tf.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, tensor_reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [ ]:
# Transpose

a = tf.range(8)
a = tf.reshape(a, [4, 2])
transpose = tf.einsum('ij -> ji', a)
print(a)
print(transpose)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]], shape=(4, 2), dtype=int32)
tf.Tensor(
[[0 2 4 6]
 [1 3 5 7]], shape=(2, 4), dtype=int32)


In [ ]:
# Bilinear transformation

a = tf.random.normal([2, 3])
b = tf.random.normal([3, 3, 4])
c = tf.random.normal([2, 4])
bilinear_transform = tf.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear_transform)

tf.Tensor(
[[-0.17270324 -0.5429104   0.37630606]
 [ 1.2421558   0.00637581 -0.3373881 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[ 0.7742922  -1.0066106  -0.04442318  0.73226094]
  [-1.5233927  -0.53423685  2.2534237   0.49974176]
  [ 1.1917588  -1.0977249  -1.0606365   0.21791953]]

 [[ 0.65510654  0.12409268  0.38059717 -0.44599015]
  [-0.68946207 -0.6839943  -0.05060837 -2.5965774 ]
  [ 0.06529208  2.6057663  -1.652664    1.0221677 ]]

 [[-1.9080431   0.13037935  0.27996024  0.02008066]
  [ 0.24206053 -1.0404192   0.55717236 -0.46767712]
  [-1.0593919  -0.2217956   0.52762204 -0.23525468]]], shape=(3, 3, 4), dtype=float32)
tf.Tensor(
[[-0.00973633 -1.5148017  -1.6184989  -0.5454428 ]
 [-0.5452406  -0.02200092  0.52320296 -0.1824027 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 2.697805   -1.9704584  -0.53497136]
 [-0.26765075  0.29265517  1.1636634 ]], shape=(2, 3), dtype=float32)


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bM = tf.random.normal([7])
br = tf.random.normal([7]) 
w = tf.random.normal([7])
# [hidden_dimension x hidden_dimension]
WY = tf.random.normal([7, 7])
Wh = tf.random.normal([7, 7])
Wr = tf.random.normal([7, 7])
Wt = tf.random.normal([7, 7])

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = tf.einsum('ik, kl -> il', ht, Wh) + tf.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = tf.expand_dims(tmp, 1)
  tmp_tiled = tf.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = tf.tanh(tf.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bM)
  
  # [batch_size x sequence_length]
  at = tf.nn.softmax(tf.einsum('ijk, k -> ij', Mt, w)) 
  
  # [batch_size x hidden_dimension]
  rt = tf.einsum('ijk, ij -> ik', Y, at) + tf.tanh(tf.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = tf.random.normal([3,5,7])
# [batch_size x hidden_dimension]
ht = tf.random.normal([3, 7])
rt1 = tf.random.normal([3, 7])

rt, at = attention(Y, ht, rt1)

print(at)

tf.Tensor(
[[0.05754606 0.1306329  0.05376851 0.03502229 0.7230302 ]
 [0.05213095 0.1951361  0.32913536 0.33406416 0.08953349]
 [0.48701498 0.07361506 0.19982888 0.01586944 0.22367163]], shape=(3, 5), dtype=float32)


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return tf.expand_dims(zl, 1) + tf.tanh(tf.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = tf.random.normal([2, 3])
# Parameters - [num_actions x hidden_dimension]
b = tf.random.normal([5, 3])
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = tf.random.normal([5, 3, 3])

transition(zl)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[ 1.1316481 , -1.2434161 , -1.9558408 ],
        [ 0.66638875,  0.68937516, -0.23515421],
        [ 0.6967683 , -1.278102  , -1.4446002 ],
        [ 0.96370816, -0.5416503 , -0.10703498],
        [ 0.30694658, -1.0906249 , -0.10415691]],

       [[ 2.2245402 , -0.72556   , -2.2052698 ],
        [ 0.30694443,  1.1429543 , -0.8224186 ],
        [ 0.43862176, -0.71575177, -2.6624305 ],
        [ 2.2352982 ,  0.5453552 , -0.760113  ],
        [ 2.271305  , -0.7055013 , -0.75808597]]], dtype=float32)>