<a href="https://colab.research.google.com/github/saipragna25/deep-learning-assignment--2/blob/main/DLA2bNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Scalar vector multiplication

a = np.array([5])
b = np.array([4, 7, 6, 8])
c = np.einsum('i, i -> i', a, b)
print(a)
print(b)
print(c)

[5]
[4 7 6 8]
[20 35 30 40]


In [ ]:
# Vector vector multiplication

a = np.random.randn(5, 8)
b = np.random.randn(8, 4)
c = np.einsum('ij, jk -> ik', a, b)
print(a)
print(b)
print(c)

[[ 1.3960585   0.97844126  0.88753938  0.80409882 -0.6088345  -1.50380594
   0.96206482  0.15230726]
 [ 0.55791506 -1.96737894 -0.39298678 -0.09845789 -1.36671916 -0.80223798
   0.60903442 -0.46704067]
 [ 0.92375638 -1.28373665  0.59480626  1.80767792 -0.66204232 -0.86241941
  -0.23920418  0.14108358]
 [-1.14489837  0.66840162 -1.9954993   1.15098781  0.15940575  0.17919279
   1.23454932  0.80117634]
 [ 0.19731606  0.07508205  0.61144933 -0.01749494  1.75190351 -0.6435802
  -0.2487277  -1.36656391]]
[[-7.82354368e-02  2.03539969e+00 -8.06017899e-02  6.30980878e-01]
 [ 8.31554115e-01  7.76085844e-01 -1.86148575e+00 -3.85638669e-01]
 [ 6.98574032e-01 -6.90867944e-01 -8.89450413e-01 -9.45742883e-01]
 [ 7.65320379e-01  2.11899076e-01  2.69447964e-01 -8.56345693e-01]
 [ 5.44349993e-01  1.21686122e+00 -4.64659858e-01  1.70699176e+00]
 [-8.28761390e-02  1.37393193e+00  3.54487614e-01  1.08984428e+00]
 [ 1.78937431e-03  1.07578912e+00  1.09592884e+00 -3.51507907e-01]
 [-1.50385515e-01  1.39217

In [ ]:
# Outer product

a = np.arange(2, 5)
b = np.arange(4, 7)  
op = np.einsum('i,j -> ij', a, b)
print(a)
print(b)
print(op)

[2 3 4]
[4 5 6]
[[ 8 10 12]
 [12 15 18]
 [16 20 24]]


In [ ]:
# Scalar dot product

a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
sd = np.einsum('ij, jk ->', a, b)
print(a)
print(b)
print(sd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]
204


In [ ]:
# Hadamard product

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
hp = np.einsum('ij, ij -> ij', a, b)
print(a)
print(b)
print(hp)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  7 16]
 [27 40 55]]


In [ ]:
# Batch matrix multiplication

a = np.random.randn(3, 3, 2)
b = np.random.randn(3, 2, 2)
batch_matrix_mul = np.einsum('bij, bjk -> bik', a, b)
print(a)
print(b)
print(batch_matrix_mul)

[[[ 0.41614877 -0.46901919]
  [ 1.92047587  1.19125178]
  [-1.1584899  -0.00621304]]

 [[ 1.03124456 -0.18659855]
  [ 1.04759456 -0.50662681]
  [-0.95043172 -0.16957041]]

 [[ 2.44529083  0.48817838]
  [ 0.26134204  0.72768367]
  [-0.89990455 -0.62149405]]]
[[[-0.22410509  0.40907658]
  [-0.656979   -0.89062235]]

 [[ 1.09867099 -1.9657315 ]
  [ 0.96914991 -0.14168104]]

 [[ 0.07061716  0.21275714]
  [ 0.25630016  0.95805815]]]
[[[ 0.2148747   0.58795569]
  [-1.21301582 -0.27533376]
  [ 0.26370533 -0.46837761]]

 [[ 0.9521565  -2.00071244]
  [ 0.65996442 -1.98751021]
  [-1.2085509   1.89231848]]

 [[ 0.29779969  0.98795636]
  [ 0.20496067  0.75276566]
  [-0.22283773 -0.78688856]]]


In [ ]:
# Tensor reduction

a = np.random.randn(2, 3, 5, 7)
b = np.random.randn(4, 1, 3, 11, 5)
tensor_reduction = np.einsum('pqrs, tuqvr -> pstuv', a, b)
print(a.shape, b.shape, tensor_reduction.shape)

(2, 3, 5, 7) (4, 1, 3, 11, 5) (2, 7, 4, 1, 11)


In [ ]:
# Transpose

a = np.arange(6).reshape(2, 3)
transpose = np.einsum('ij -> ji', a)
print(a)
print(transpose)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# Bilinear transformation

a = np.random.randn(2, 3)
b = np.random.randn(3, 3, 4)
c = np.random.randn(2, 4)
bilinear_transform = np.einsum('ik, jkl, il -> ij', a, b, c)
print(a)
print(b)
print(c)
print(bilinear_transform)

[[ 0.9749097   0.18706504  1.30561941]
 [-1.2511083   1.60841784 -1.54006544]]
[[[ 1.00963028  1.53429206 -0.23501251 -0.46193143]
  [-0.29852684  0.64917725 -0.86979383  0.17083853]
  [ 0.33443553 -0.56488399  0.17252672  1.1085493 ]]

 [[-0.87655283  0.12576031 -0.98102679  0.29699933]
  [ 0.11154076 -0.50190726 -0.7487725   0.30652496]
  [-0.31151759 -0.17969732  0.03048806 -1.49243936]]

 [[-1.69983777 -0.1950042  -0.39693056  0.87909681]
  [ 0.70947646  0.33577033 -1.92853131 -0.51732548]
  [-1.37733773  0.49051505 -0.59943298 -0.28207507]]]
[[ 0.65646287  0.23187594 -0.097599   -0.78253401]
 [ 1.19056613 -1.91934307  2.54484003 -0.78192966]]
[[ 0.31118212  0.49446018 -2.2196586 ]
 [-5.49820282  1.45761876  3.25129634]]


In [ ]:
# Attention

# Parameters
# [hidden_dimension]
bm = np.random.randn(7)
br = np.random.randn(7) 
w = np.random.randn(7)
# [hidden_dimension x hidden_dimension]
WY = np.random.randn(7, 7)
Wh = np.random.randn(7, 7)
Wr = np.random.randn(7, 7)
Wt = np.random.randn(7, 7)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = np.einsum('ik, kl -> il', ht, Wh) + np.einsum('ik, kl -> il', rt1, Wr)

  tmp_expanded = np.expand_dims(tmp, 1)
  tmp_tiled = np.tile(tmp_expanded, [1, Y.shape[1], 1]) 
  Mt = np.tanh(np.einsum('ijk, kl -> ijl', Y, WY) + tmp_tiled + bm)
  
  # [batch_size x sequence_length]
  at = np.einsum('ijk, k -> ij', Mt, w)
  at = np.exp(at)/np.sum(np.exp(at))
  
  # [batch_size x hidden_dimension]
  rt = np.einsum('ijk, ij -> ik', Y, at) + np.tanh(np.einsum('ij, jk -> ik', rt1, Wt) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = np.random.randn(3,5,7)
# [batch_size x hidden_dimension]
ht = np.random.randn(3, 7)
rt1 = np.random.randn(3, 7)

rt, at = attention(Y, ht, rt1)

print(at)

[[0.05656115 0.01801595 0.05694506 0.04890405 0.02830681]
 [0.04765451 0.06870138 0.03728298 0.05488482 0.07058679]
 [0.04342242 0.18440144 0.0916009  0.0545797  0.13815204]]


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return np.expand_dims(zl, 1) + np.tanh(np.einsum('bk, aki -> bai', zl, W) + b)

# Inputs - [batch_size x hidden_dimension]
zl = np.random.rand(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = np.random.rand(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = np.random.rand(5, 3, 3)

transition(zl)

array([[[1.9119112 , 0.82990175, 1.38159061],
        [1.89529432, 0.99052212, 1.38517942],
        [1.52860945, 0.71923831, 1.12245308],
        [1.7842578 , 0.85589596, 1.3686122 ],
        [1.88244034, 0.85534427, 1.42833963]],

       [[0.98441302, 0.8721689 , 1.30300321],
        [0.96333069, 1.06523836, 1.24674372],
        [0.7292631 , 0.66817753, 0.99187074],
        [0.85203425, 0.83063427, 1.07830809],
        [0.82394384, 0.63627892, 1.17947918]]])